# Generated by Django 4.2 on 2023-04-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quiz", "0001_initial"),
        ("student", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentTable",
            fields=[
                ("ExamID", models.AutoField(primary_key=True, serialize=False)),
                ("ExamName", models.CharField(max_length=150)),
                ("ExamDuration", models.DecimalField(decimal_places=2, max_digits=500)),
                ("Totalques", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "Instruction",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "Ccode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.coursetable",
                    ),
                ),
                (
                    "Programme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.programmetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "prefix",
                    models.CharField(
                        choices=[
                            ("Mr.", "Mr."),
                            ("Mrs.", "Mrs."),
                            ("Dr.", "Dr."),
                            ("Ms.", "Ms."),
                            ("Miss", "Miss"),
                        ],
                        max_length=10,
                    ),
                ),
                ("user", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20)),
                ("smartID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.departmenttable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Max_Total_Mark",
                    models.DecimalField(decimal_places=2, max_digits=500),
                ),
                (
                    "TotalMarkObtained",
                    models.DecimalField(decimal_places=2, max_digits=500),
                ),
                ("date_attempted", models.DateTimeField(auto_now_add=True)),
                (
                    "SId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
                (
                    "TestId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.assignmenttable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionTable",
            fields=[
                ("QuesID", models.AutoField(primary_key=True, serialize=False)),
                ("Ques", models.CharField(max_length=2000)),
                ("Option1", models.CharField(max_length=1000)),
                ("Option2", models.CharField(max_length=1000)),
                ("option3", models.CharField(max_length=1000)),
                ("option4", models.CharField(max_length=1000)),
                (
                    "ans",
                    models.CharField(
                        choices=[
                            ("Option 1", "Option 1"),
                            ("Option 2", "Option 2"),
                            ("Option 3", "Option 3"),
                            ("Option 4", "Option 4"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("max_mark", models.DecimalField(decimal_places=2, max_digits=50)),
                ("neg_mark", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "TestID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.assignmenttable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Max_mark", models.DecimalField(decimal_places=2, max_digits=500)),
                (
                    "Mark_Obtained",
                    models.DecimalField(decimal_places=2, max_digits=500),
                ),
                (
                    "QId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.questiontable",
                    ),
                ),
                (
                    "SId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
                (
                    "TestID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.assignmenttable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptionSelected",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans_selected", models.CharField(max_length=10)),
                (
                    "QuestionId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.questiontable",
                    ),
                ),
                (
                    "SId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
                (
                    "TestId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.assignmenttable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignmenttable",
            name="Tid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher.teacher",
            ),
        ),
    ]
